/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LXVBznsJGQI
 */
import { useRef } from "react"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function ReferralLink({
  value,
  className,
}: {
  value: string
  className?: string
}) {
  const ref = useRef<HTMLInputElement>(null)
  return (
    <div
      className={cn(
        "flex w-full max-w-md items-center space-x-2 rounded-lg border border-gray-200 p-1",
        className
      )}
    >
      <Input
        className="rounded-lg border-0 font-mono text-sm"
        disabled
        id="disabled-input-link"
        value={value}
        ref={ref}
      />
      <Button
        className="h-8 px-3 text-xs leading-none"
        onClick={() => {
          if (ref.current) {
            ref.current.select()
            ref.current.setSelectionRange(0, 99999)
            navigator.clipboard.writeText(ref.current.value)
          }
        }}
        variant="outline"
      >
        Copy
      </Button>
    </div>
  )
}
