/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wvvR7xJf69u
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function SearchBar({
  onSearch,
}: {
  onSearch?: (query: string) => void
}) {
  return (
    <form
      onSubmit={(e) => {
        e.preventDefault()
        const query = new FormData(e.currentTarget).get("search") as string
        if (onSearch) onSearch(query)
      }}
    >
      <div className="flex w-full items-center space-x-2 rounded-lg border border-lime-700 px-2.5 py-1.5">
        <Input
          className="w-full border-0 bg-transparent focus:border-0 focus-visible:ring-0 focus-visible:ring-transparent focus-visible:ring-offset-0"
          placeholder="Search"
          type="search"
          name="search"
        />
        <Button size="icon" type="submit" variant="ghost">
          <SearchIcon className="h-4 w-4" />
          <span className="sr-only">Search</span>
        </Button>
      </div>
    </form>
  )
}

function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
